
project_id = "yuqqexlqizgzhrjydnen"

[functions.generate-audit]
verify_jwt = true

# Enable resource embedding for all functions
# This allows the functions to access resources and bypass RLS policies
[functions]
[functions.options]
db_unsafe_allow_all = true

# Grant database access to all functions
[api]
[api.options]
db_unsafe_allow_all = true
