// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yuqqexlqizgzhrjydnen.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1cXFleGxxaXpnemhyanlkbmVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MjA3NzEsImV4cCI6MjA2MjM5Njc3MX0.whRQGcG0vHCv3Q2mdieR9N5f9h3F16dXgERd7DQxsH0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);